ticketsys/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :issues
  
  resources :tickets do
    member do
      get 'assign'
      post 'add'
      delete 'remove'
      put 'submit'
    end
  end
  
  get '/ticketsys/tickets' => 'ticketsys_tickets#index'
  put '/ticketsys/tickets/:id/assign' => 'ticketsys_tickets#assign', as: :assign
  put '/ticketsys/tickets/:id/working' => 'ticketsys_tickets#working', as: :working
  put '/ticketsys/tickets/:id/worked' => 'ticketsys_tickets#worked', as: :worked
  put '/ticketsys/tickets/:id/complete' => 'ticketsys_tickets#complete', as: :complete
  
  root "tickets#index"
 end

ticketsys/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
     if user.email == "divackc@yahoo.com" # you can add any condition
        can :manage, :all
     end
    if user.superadmin_role?
      can :manage, :all
      can :dashboard, all
      can :access, :rails_admin       # only allow admin users to access Rails Admin
    end
    if user.supervisor_role?
      can :manage, User
    end
  end
end

ticketsys/app/models/admin.rb
class Admin < ActiveRecord::Base
devise :database_authenticatable, :trackable, :timeoutable, :lockable  
attr_accessible :email, :password, :password_confirmation
end

ticketsys/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ticketsys/app/models/issue.rb
class Issue < ApplicationRecord
    has_many :ticket_issue
    has_many :tickets, through: :ticket_issue 
end

ticketsys/app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :user
    has_many :ticket_issues
    has_many :tickets, through: :ticket_issues
end

ticketsys/app/models/ticket_issue.rb
class TicketIssue < ApplicationRecord
    belongs_to :ticket
    belongs_to :issue
end

ticketsys/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tickets
end

ticketsys/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ticketsys/app/controllers/issues_controller.rb
class IssuesController < ApplicationController
    before_action :authenticate_user!
    # load_and_authorize_resource
    # load_and_authorize_resource :only => [:new, :edit]
    # skip_authorize_resource :only => :index
   
    def index
        @issues = Issue.all
    end

    def new
        @issue = Issue.new
    end
    
    def create
        issue = Issue.new
        issue.name = params[:issue][:name]
        issue.description = params[:issue][:description]
        issue.picture = params[:issue][:picture]
        issue.save
        redirect_to issues_path
    end

    def edit
        @issue = Issue.find(params[:id])
    end
    
    def update
        issue = Issue.find(params[:id])
        issue.name = params[:issue][:name]
        issue.description = params[:issue][:description]
        issue.picture = params[:issue][:picture]
        issue.save
        redirect to issues_path
    end
    
    def delete
        issue = Issue.find(params[:id])
        issue
    end
end

ticketsys/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @tickets = Ticket.where(user_id: current_user.id)
    end
    
    def show
    end
    
    def new
        @ticket = Ticket.new
    end
    
    def create
        @ticket = Ticket.new
        @ticket.pcname = params[:ticket][:pcname]
        @ticket.name = params[:ticket][:name]
        @ticket.extension = params[:ticket][:extension]
        @ticket.status = 'created'
        @ticket.user_id = current_user.id
        @ticket.save
        redirect_to assign_ticket_path(@ticket)
    end
    
    def assign
        @ticket = Ticket.find(params[:id])
        @issues = Issue.all
    end
    
    def add
        @ticket = Ticket.find(params[:id])
        ticket_issue = TicketIssue.new
        ticket_issue.issue_id = params[:issue_id]
        ticket_issue.ticket_id = params[:id]
        ticket_issue.save
        redirect_to assign_ticket_path(@ticket)
    end
    
    def remove
        @ticket = Ticket.find(params[:id])
        ticket_issue = TicketIssue.find(params[:ticket_issue_id])
        ticket_issue.destroy
        redirect_to assign_ticket_path(@ticket)
    end
    
    def submit
        @ticket = Ticket.find(params[:id])
        @ticket.status = 'submitted'
        @ticket.save
        redirect_to tickets_path
    end
    
end

ticketsys/app/controllers/ticketsys_tickets_controller.rb
class TicketsysTicketsController < ApplicationController
    
    def index
        @tickets = Ticket.where(status: ['submitted', 'assigned', 'working', 'worked'])
    end
    
    def assign
        @ticket =  Ticket.find(params[:id])
        @ticket.status = 'assigned'
        @ticket.save
        redirect_to ticketsys_tickets_path
    end
    
    def working
        @ticket =  Ticket.find(params[:id])
        @ticket.status = 'working'
        @ticket.save
        redirect_to ticketsys_tickets_path
    end
    
    def worked
        @ticket =  Ticket.find(params[:id])
        @ticket.status = 'worked'
        @ticket.save
        redirect_to ticketsys_tickets_path
    end
    
    def complete
        @ticket =  Ticket.find(params[:id])
        @ticket.status = 'complete'
        @ticket.save
        redirect_to ticketsys_tickets_path
    end
    
end

ticketsys/app/helpers/application_helper.rb
module ApplicationHelper
end

ticketsys/app/helpers/issues_helper.rb
module IssuesHelper
end

ticketsys/app/helpers/tickets_helper.rb
module TicketsHelper
end

ticketsys/app/helpers/ticketsys_tickets_helper.rb
module TicketsysTicketsHelper
end

ticketsys/app/views/issues/_form.html.erb
<%= form_for Issue.new do |f| %>
<div>
    <%= f.text_field :name, placeholder: 'Affected System' %>
</div>
<div>
    <%= f.text_area :description, placeholder: 'Description'  %>
</div>
<%= f.text_field :picture, placeholder: 'Picture'  %>
<%= f.submit 'Save' %>
<% end %>

ticketsys/app/views/issues/application.html.erb
<%= link_to "Home", root_path %>
<%= link_to "Issues", issues_path %>

ticketsys/app/views/issues/edit.html.erb
<h2>EDIT SYSTEM</h2>
<%= render 'form' %>

ticketsys/app/views/issues/index.html.erb
<%= link_to 'New', new_issue_path %>

<% @issues.each do |issue| %>
<div class="media mt-4">
        <span class="border border-white">
    <div>
        <%= image_tag issue.picture, height: 100 %>
    </div>
        <div>
           <%= issue.name %> 
        </div>
        <div>
            <p><%= issue.description %></p>
       </div>
        </span>
</div>
     <%= link_to 'Edit', edit_issue_path(issue) %>
<% end %>    

ticketsys/app/views/issues/new.html.erb
<h2> NEW SYSTEM</h2>
<%= render 'form' %>

ticketsys/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ticketsys</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

ticketsys/app/views/tickets/assign.html.erb
<div class="row">
    <div class="col-8">
        <h2>Systems</h2>
        <% @issues.each do |issue| %>
            <div class="media mt-4">
                <span class="border border-dark">
                <%= image_tag issue.picture, height: 100, width: 100, class: 'mr-3' %>
                </span>
                <div class="media-body">
                    <h5 class="mt-0">
                        <%= issue.name %>
                        <%= link_to 'Add', add_ticket_path(@ticket, issue_id: issue.id), method: :post, class: 'btn btn-primary btn-sm' %>
                    </h5>
                    <%= issue.description %>
                </div>
            </div>
        <% end %>
</div>
<div class="col-4">
          <h2>Current Ticket</h2>
          <% @ticket.ticket_issues.each do |ticket_issue| %>
                 <div class="media mt-4">
                     <span class="border border-dark">
                    <%= image_tag ticket_issue.issue.picture, height: 50, width: 50, class: 'mr-3' %>
                    </span>
                    <div class="media-body">
                        <h5>
                            <%= ticket_issue.issue.name %>
                            <%= link_to 'Remove', remove_ticket_path(@ticket, ticket_issue_id: ticket_issue.id), method: :delete, class: 'btn btn-danger btn-sm' %>
                        </h5>
                    </div>
                    
                  </div>
                <% end %> 
                <%= link_to 'Submit', submit_ticket_path(@ticket), method: :put, class: 'btn btn-success' %>
            </div>
    </div>

ticketsys/app/views/tickets/index.html.erb
<%= link_to 'New Ticket', new_ticket_path %>

<% @tickets.each do |ticket| %>
        <div class="media mt-4">
        <span class="border border-white">
        <%= ticket.pcname %>
        <%= ticket.name %>
        <%= ticket.extension %>
        <%= ticket.status %>
        </span>
        </div>
    <% end %>

ticketsys/app/views/tickets/new.html.erb
<%= form_for @ticket do |f| %>
<%= f.text_field :name, placeholder: 'Name' %>
<%= f.text_field :pcname, placeholder: 'PC Name' %>
<%= f.text_field :extension, placeholder: 'Extension' %>
<%= f.submit 'Create' %>
<% end %>

ticketsys/app/views/ticketsys_tickets/index.html.erb
<% @tickets.each do |ticket| %>

    <div class= "row">
        <div class="col-md-4">
            <%= ticket.status %>
        </div>
    </div>
        <div class="col-6">
            <%= ticket.name %>
            <%= ticket.pcname %>
        </div>
        <div class="col-3" >
            <% if ticket.status == 'submitted' %>
                <%= link_to 'Assign', assign_path(ticket), method: :put, class: 'btn btn-sm btn-secondary' %>
            <% elsif ticket.status == 'assigned' %>
                <%= link_to 'Working', working_path(ticket), method: :put, class: 'btn btn-sm btn-secondary' %>  
            <% elsif ticket.status == 'working' %>
                <%= link_to 'Worked', worked_path(ticket), method: :put, class: 'btn btn-sm btn-secondary' %>  
            <% elsif ticket.status == 'worked' %>
                <%= link_to 'Complete', complete_path(ticket), method: :put, class: 'btn btn-sm btn-secondary' %>
            <% end %> 
        </div>
        
        <% if ticket.status == 'assigned' %>
            <% ticket.ticket_issues.each do |ticket_issue| %>
                 <div class="col-md-4">
                    <%= image_tag ticket_issue.issue.picture, height: 50, width: 50, class: 'mr-3' %>
                    <div class="media-body">
                        <h6>
                            <%= ticket_issue.issue.name %>
                        </h6>
                    </div>
                 </div>
            <% end %>
        <% end %>
        </span>
<% end %>