school/config/routes.rb
Rails.application.routes.draw do
  get '/courses/new' => 'courses#new'
  post '/courses' => 'courses#create'
  get '/courses' => 'courses#index'
  get '/courses/:id' => 'courses#edit'
  post '/courses/:id' => 'courses#update'
  get '/courses/delete' => 'courses#delete'
  get '/courses/show' => 'courses#show'
  
  
  get '/students/new' => 'students#new'
  post '/students' => 'students#create'
  get '/students' => 'students#index'
  
 # get '/' => 'courses#index'
  root 'courses#index'
end

school/app/models/course.rb
class Course < ApplicationRecord
    has_many :students
end

school/app/models/student.rb
class Student < ApplicationRecord
    belongs_to :course
end

school/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    def new 
    end
    
    def create
        course = Course.new
        course.name = params[:name]
        course.location = params[:location]
        course.description = params[:description]
        course.save
        redirect_to '/courses'
    end
    
    def index
        @courses= Course.all
    end
    
    def edit
        @course = Course.find(params[:id])
    end
    
    def update
        course = Course.find(params[:id])
        course.name = params[:name]
        course.location = params[:location]
        course.description = params[:description]
        course.save
        redirect_to '/courses'
    end
    
    def delete
        course = Course.find(params[:id])
        course.destroy
        redirect_to '/courses'
    end
    
    def show
        
    end
    
end

school/app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def new 
        @courses = Course.all
    end
    
    def create
        student = Student.new
        student.first_name = params[:first_name]
        student.last_name = params[:last_name]
        student.picture = params[:picture]
        student.course_id = params[:course_id]
        student.save
        redirect_to '/students'
    end
    
    def index
        @students = Student.all
    end
    
    def edit
    end
    
    def update
    end
    
    def delete
    end
end

school/app/helpers/courses_helper.rb
module CoursesHelper
end

school/app/helpers/students_helper.rb
module StudentsHelper
end

school/app/views/courses/edit.html.erb
<form action="/courses/<%= @course.id %>" method="post">
        <div>
        <input type="text" name="name" value="<%= @course.name %>" placeholder="Course Name">
    </div>
    <div>
        <input type="text" name="location" value="<%= @course.location %>" placeholder="Location">
    </div>
    <div>
        <textarea name="description"><%= @course.description %></textarea>
    </div>
    <div>
        <input type="submit" value="Save">
    </div>
</form>

school/app/views/courses/index.html.erb
<a href="<%= courses_new_path %>">New</a>
<% @courses.each do |course| %>
    <div>
        <h4><%= course.name %></h4>
        Location: <%= course.location %>
        <p>
            <%= course.description %>
        </p>
        <a href="/courses/<%= course.id %>">Edit</a>
        <a href="/courses/show?id=<%= course.id %>">Show</a>
    </div>

<% end %>

school/app/views/courses/new.html.erb
<form action="/courses" method="post">
    <div>
        <input type="text" name="name" placeholder="Course Name">
    </div>
    <div>
        <input type="text" name="location" placeholder="Location">
    </div>
    <div>
        <textarea name="description"></textarea>
    </div>
    <div>
        <input type="submit" value="Save">
    </div>
</form>

school/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>School</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

school/app/views/students/index.html.erb
<a href="/students/new">New Student</a>

<% @students.each do |student| %>
    <div>
        <%= student.first_name %> <%= student.last_name %>
    </div>
<% end %>
    

school/app/views/students/new.html.erb
<form action="/students" method= "post">
    <div>
        <input type="text" name="first_name" placeholder="First Name">
    </div>
    <div>
        <input type="text" name="last_name" placeholder="Last Name">
    </div>
    <div>
        <input type="text" name="picture" placeholder="Picture">
    </div>
    <div>
        <select name="course_id">
            <% @courses.each do |course| %>
                 <option value="<%= course.id %>"><%= course.name %></option>
             <% end %>
        </select>
    </div>
    <div>
        <input type="submit" value="Save">
    </div>
</form>